In [ ]:
a=4.5
print(type(a))

b=round(a) #반올림함수(오사오입)
print(b)
print(type(b))

<class 'float'>
4
<class 'int'>


In [6]:
a=[1,2,3,4,5]
print(min(a))
print(max(a))

1
5


In [14]:
a=np.array([10,20,30,40,50])
print(a+10)

[20 30 40 50 60]


In [ ]:
import numpy as np

items=range(10,51,10)
arr=np.array(items)
print(arr)
print(arr.shape) #차원->1차원,5열

[10 20 30 40 50]
(5,)


In [ ]:
import numpy as np

items2=[range(1,6), range(10,51,10)]
arr2=np.array(items2)
print(arr2)
print(arr2.shape) #2차원, 2행5열

list[[range(1, 6), range(10, 51, 10)]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
(2, 5)


In [10]:
import numpy as np

# numpy.sqrt()는 제곱근
print(np.sqrt(100))
print(np.sqrt(16))
print(f'{np.sqrt(7):.2f}')
print(np.sqrt(2))

10.0
4.0
2.65
1.4142135623730951


In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.multiply(a,b))
print(np.max(a))
print(np.min(b))
print(np.argmax(a))
print(np.argmin(b))


[ 4 10 18]
3
4
2
0


In [10]:
import numpy as np

arr1 = np.array([[70,80],[195,185]])
arr2 = np.array([[50,60],[70,80]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2) #실수몫
print(arr1 // arr2) #정수몫-소수점이하 버림
print(np.round(arr1/arr2,2)) #넘파이 반올림(값, 소수이하자리수)

print(arr2.shape)

[[120 140]
 [265 265]]
[[ 20  20]
 [125 105]]
[[ 3500  4800]
 [13650 14800]]
[[1.4        1.33333333]
 [2.78571429 2.3125    ]]
[[1 1]
 [2 2]]
[[1.4  1.33]
 [2.79 2.31]]
(2, 2)
